'use strict';
// Each eight-beat phrase has a four-beat call and a four-beat response.
const DokkaebiChart={
 stages:[
 {name:'달빛 입문',level:'쉬움',bpm:84,rounds:6,hints:6,flour:[],baitRounds:[],duet:5,desc:'정박과 짧은 따라 치기 · 힌트가 끝까지 보여요',patterns:[[0,2],[0,1,3],[0,2,3],[0,1,2],[0,1.5,3],[0,1,2,3]]},
 {name:'장난꾸러기 떡방',level:'보통',bpm:100,rounds:8,hints:2,flour:[4,5],baitRounds:[2,5],duet:6,desc:'반 박 엇박 · 에취 가짜 신호 · 밀가루 구름',patterns:[[0,1,2],[0,1.5,3],[0,.5,2,3],[.5,1.5,2.5],[0,1,2.5,3],[0,.5,1.5,3],[0,1.5,2,3],[0,.5,1.5,2.5,3,3.5]]},
 {name:'도깨비 달밤 축제',level:'어려움',bpm:116,rounds:10,hints:1,flour:[3,4,7,8],baitRounds:[2,5,7],duet:8,desc:'4분의 1박 변화 · 긴 리듬 기억 · 마지막 합주',patterns:[[0,.5,1.5,2.5,3],[0,.75,1.5,2.75,3.5],[0,.5,2,3],[.5,1.25,2,2.75,3.5],[0,.75,1.5,2.5,3.25],[0,.5,1.5,3],[0,.5,1.25,2,2.75,3.5],[0,.5,2,3],[0,.75,1.5,2.25,3],[0,.5,1,1.75,2.5,3,3.5]]}
 ],
 patterns:[[0,1,2],[0,1.5,3],[0,.5,2,3],[.5,1.5,2.5],[0,1,2.5,3],[0,.5,1.5,3],[0,1.5,2,3],[0,.5,1.5,2.5,3,3.5]],
 build(rounds=null,stage=1){const config=this.stages[stage];rounds=rounds??config.rounds;const calls=[],notes=[],baits=[];for(let r=0;r<rounds;r++){const start=4+r*8;for(const p of config.patterns[r]){calls.push({beat:start+p,round:r});notes.push({beat:start+4+p,round:r,done:false});if(r>=config.duet)calls.push({beat:start+4+p,round:r});}if(config.baitRounds.includes(r)){const fake=r===5?2.25:1.25;baits.push({beat:start+fake,round:r,call:true,done:false});baits.push({beat:start+4+fake,round:r,call:false,done:false});}}return{calls,notes,baits,total:4+rounds*8,config,rounds,stage};},
 accuracy(r){return Math.max(0,Math.round((r.perfect+r.good*.65-r.extras*.2)/r.notes.length*100));}
};
(() => {
 const nav=document.querySelector('.game-tabs'),tab=document.createElement('button');tab.dataset.game='dokkaebi';tab.textContent='✦ 도깨비 떡방아';tab.setAttribute('aria-pressed','false');nav.append(tab);
 const panel=document.createElement('section');panel.id='dokkaebiMode';panel.hidden=true;
 panel.innerHTML=`<div id="dkMenu"><div class="intro"><div><p class="eyebrow">LISTEN → REMEMBER → PLAY</p><h1>도깨비 떡방아</h1><p>사부가 친 박자를 기억했다가, 내 차례에 똑같이!<br>“에취!”에는 손을 멈춰야 해요.</p></div></div><div id="dkStages" class="dk-stages" role="group" aria-label="떡방아 난이도 선택"></div><div class="dk-preview"><canvas id="dkPreview" width="900" height="430" aria-label="도깨비 사부와 제자가 떡방아를 찧는 달밤"></canvas><div><span class="eyebrow">달빛 아래 떡 수업</span><h2 id="dkStageTitle">쿵, 쿵… 이제 네 차례!</h2><p id="dkStageInfo"></p><ol><li>사부의 네 박을 먼저 들어요.</li><li>다음 네 박에 그대로 따라 쳐요.</li><li>마지막에는 사부와 함께 합주해요.</li></ol><p>보통·어려움에서는 밀가루가 힌트를 가려요.<br>화면보다 귀를 믿어 보세요.</p><div class="dk-actions"><button id="dkStart" class="primary">떡 만들기 시작 →</button><button id="dkPractice" class="quiet">천천히 연습 · 80%</button><button id="dkDemo" class="quiet">시범 먼저 보기</button></div><p id="dkBest"></p></div></div></div><div id="dkPlay" hidden><div class="game-top"><button id="dkBack" class="quiet">← 떡방아 소개</button><strong id="dkRound">첫 수업</strong><button id="dkSettings" class="quiet">소리 · 보정</button><button id="dkPause" class="quiet">Ⅱ 일시정지</button></div><div class="stats"><div><small>SCORE</small><b id="dkScore">0</b></div><div><small>COMBO</small><b id="dkCombo">0</b></div><div><small>RICE CAKE</small><b id="dkRice">작은 경단</b></div></div><div class="dk-arena"><div id="dkTurn">먼저 들어요</div><canvas id="dkWorld" width="900" height="430" aria-label="사부의 박자를 따라 치는 떡방아 게임"></canvas><div id="dkFeedback" role="status">준비!</div><div id="dkBeats" aria-label="네 박자 안내"></div><div id="dkPauseCover" hidden><h2>잠깐 쉬는 중</h2><button id="dkResume" class="primary">▶ 계속하기</button></div></div><div class="dk-controls"><button id="dkTap">쿵! <kbd>SPACE</kbd></button><p id="dkHint">사부의 차례에는 듣기만 · 내 차례에는 스페이스바 또는 터치</p></div></div><dialog id="dkResult"><p class="eyebrow">MOONLIGHT RICE CAKE</p><h2 id="dkResultTitle"></h2><p id="dkSummary"></p><p id="dkDetail"></p><p id="dkTip" class="next-tip"></p><button id="dkNext" class="primary">다음 라운드 →</button><button id="dkRetry" class="quiet">다시 떡 만들기</button><button id="dkDone" class="quiet">돌아가기</button></dialog>`;
 nav.after(panel);let state=null,timer=0,raf=0,generation=0,active=false,record=null,selectedStage=0,stageRecords={};
 try{record=JSON.parse(localStorage.getItem('rp-dokkaebi-best')||'null');}catch{}
 try{stageRecords=JSON.parse(localStorage.getItem('rp-dokkaebi-stages')||'{}')||{};}catch{}
 if(record&&!stageRecords[1])stageRecords[1]=record;
 function selectStage(i){selectedStage=i;menu();}
 function silence(){for(const n of nodes){try{n.stop();}catch{}}nodes.clear();}
 function stopGame(){generation++;clearInterval(timer);cancelAnimationFrame(raf);timer=raf=0;state=null;silence();$('dkTap').classList.remove('pressed');$('dkResult').close();document.body.classList.remove('dk-playing');}
 function stop(){stopGame();active=false;panel.hidden=true;}
 function open(){active=true;panel.hidden=false;menu();}
 function menu(){stopGame();$('dkMenu').hidden=false;$('dkPlay').hidden=true;const config=DokkaebiChart.stages[selectedStage];record=stageRecords[selectedStage]||null;$('dkStages').innerHTML=DokkaebiChart.stages.map((v,i)=>`<button id="dkStage${i}" class="dk-stage ${i===selectedStage?'selected':''}" aria-pressed="${i===selectedStage}"><small>0${i+1} · ${v.level}</small><strong>${v.name}</strong><span>${v.bpm} BPM · ${v.rounds}번의 수업</span></button>`).join('');DokkaebiChart.stages.forEach((_,i)=>$('dkStage'+i).onclick=()=>selectStage(i));$('dkStageTitle').textContent=config.name;$('dkStageInfo').textContent=config.desc;$('dkBest').textContent=record?`이 스테이지 최고 ${record.score.toLocaleString()}점 · ${record.accuracy}%`:`${config.level} · ${config.rounds}번의 수업 · 약 ${Math.round((4+config.rounds*8)*60/config.bpm)}초`;draw($('dkPreview'),0,null);}

 function thump(t,student=false){tone(student?145:195,t,.16,.24,'triangle');tone(student?73:98,t,.2,.12,'sine');}
 function sneeze(t){noise(t,.14,.16,1500);tone(390,t,.1,.12,'sawtooth');tone(270,t+.1,.11,.09,'triangle');}
 async function start(kind){stopGame();const token=generation;try{await initAudio();}catch{$('dkBest').textContent='소리를 시작하지 못했어요. 다시 눌러 주세요.';return;}if(token!==generation||!active)return;const config=DokkaebiChart.stages[selectedStage],rounds=kind==='demo'?3:config.rounds;
  state={...DokkaebiChart.build(rounds,selectedStage),kind,spb:60/(config.bpm*(kind==='practice'?.8:1)),start:audio.currentTime+.35,tick:0,score:0,combo:0,max:0,perfect:0,good:0,miss:0,extras:0,dodged:0,down:false,paused:false,lastHit:-99,lastMiss:-99,lastFake:-99,feedbackUntil:0};
  $('dkMenu').hidden=true;$('dkPlay').hidden=false;$('dkPauseCover').hidden=true;$('dkPause').textContent='Ⅱ 일시정지';$('dkTap').disabled=kind==='demo';$('dkTap').innerHTML=kind==='demo'?'자동 시범 중':'쿵! <kbd>SPACE</kbd>';document.body.classList.add('dk-playing');window.scrollTo(0,0);timer=setInterval(schedule,25);schedule();frame();
 }
 function schedule(){if(!state||state.paused)return;const r=state;while(r.tick/4<r.total){const b=r.tick/4,t=r.start+b*r.spb;if(t>audio.currentTime+.12)break;if(t>=audio.currentTime-.02){if(b<4&&r.tick%4===0)tone(660,t,.06,.1,'sine');if(b>=4){if(r.tick%4===0)tone(hz(43+[0,0,5,7][Math.floor((b-4)/8)%4]),t,.19,.13,'triangle');if(r.tick%8===0)tone(hz(67+[0,3,7,5][Math.floor(b/2)%4]),t,.24,.085,'sine');if(r.tick%4===2)noise(t,.04,.035,5000);if((b-4)%8===3.5){tone(880,t,.09,.13,'sine');tone(1175,t+.12,.09,.11,'sine');}}
   if(r.calls.some(n=>n.beat===b))thump(t);if(r.baits.some(n=>n.beat===b))sneeze(t);
  }r.tick++;}}
 function feedback(s){$('dkFeedback').textContent=s;if(state)state.feedbackUntil=audio.currentTime+.6;}
 function judge(n,result){if(n.done)return;n.done=true;state[result]++;if(result==='miss'){state.combo=0;state.lastMiss=beat();feedback('앗! 떡이 얼굴에 붙었어요');}else{state.combo++;state.max=Math.max(state.max,state.combo);state.score+=result==='perfect'?1000:650;state.lastHit=beat();thump(audio.currentTime,true);feedback(result==='perfect'?'찰떡! PERFECT':'좋아요! GOOD');}}
 function beat(){return((state.paused?state.pauseAt:audio.currentTime)-state.start)/state.spb;}
 function hit(){if(!state||state.paused||state.kind==='demo'||state.down)return;state.down=true;$('dkTap').classList.add('pressed');const r=state,t=audio.currentTime-r.start-offset/1000,b=t/r.spb;if(b<4||b>=r.total)return;const fake=r.baits.find(n=>!n.call&&Math.abs(n.beat*r.spb-t)<.20);if(fake){r.extras++;r.combo=0;r.lastFake=beat();fake.done=true;feedback('에취는 치는 소리가 아니에요!');return;}const answer=((b-4)%8)>=3.7;if(!answer){feedback('지금은 사부 차례! 귀 기울여요');return;}let n=null,error=Infinity;for(const a of r.notes){if(a.done)continue;const e=t-a.beat*r.spb;if(Math.abs(e)<Math.abs(error)){n=a;error=e;}}if(n&&Math.abs(error)<=.16)judge(n,Math.abs(error)<=.07?'perfect':'good');else{r.extras++;r.combo=0;r.lastMiss=beat();feedback('박자를 한 번 더 떠올려요');}}
 function release(){if(state)state.down=false;$('dkTap').classList.remove('pressed');}
 function pause(){if(!state)return;release();if(state.paused){state.start+=audio.currentTime-state.pauseAt;state.paused=false;$('dkPauseCover').hidden=true;$('dkPause').textContent='Ⅱ 일시정지';}else{state.pauseAt=audio.currentTime;state.tick=Math.max(0,Math.ceil((state.pauseAt-state.start)/state.spb*4));state.paused=true;silence();$('dkPauseCover').hidden=false;$('dkPause').textContent='▶ 계속하기';}}
 function advance(){if(!state||state.paused)return;const r=state,b=beat(),t=audio.currentTime-r.start-offset/1000;for(const n of r.notes)if(!n.done){if(r.kind==='demo'&&b>=n.beat)judge(n,'perfect');else if(t>n.beat*r.spb+.18)judge(n,'miss');}for(const n of r.baits)if(!n.call&&!n.done&&t>n.beat*r.spb+.20){n.done=true;r.dodged++;}if(b>r.total+1)finish();}
 function frame(){if(!state)return;advance();if(!state)return;const r=state,b=beat(),round=Math.max(0,Math.floor((b-4)/8)),phase=((Math.max(4,b)-4)%8),answer=phase>=4;
  $('dkRound').textContent=`${r.config.level} · ${Math.min(r.rounds,round+1)} / ${r.rounds} 수업${r.kind==='practice'?' · 느린 연습':''}`;$('dkScore').textContent=r.score.toLocaleString();$('dkCombo').textContent=r.combo;$('dkRice').textContent=r.perfect+r.good>=25?'무지개 떡':r.perfect+r.good>=12?'가래떡':'작은 경단';
  const fake=r.baits.some(n=>Math.abs(n.beat-b)<.32);$('dkTurn').textContent=b<4?`준비 ${Math.max(1,4-Math.floor(Math.max(0,b)))}`:fake?'에취! 손 멈춰!':answer?(round>=r.config.duet?'함께 쿵! 마지막 합주':'네 차례! 그대로 따라 해봐'):'사부 차례 · 먼저 들어요';$('dkTurn').classList.toggle('answer',answer);if(!r.paused&&audio.currentTime>r.feedbackUntil)$('dkFeedback').textContent=r.config.flour.includes(round)?'밀가루에 가려져도 소리를 기억해요':answer?'들은 리듬을 기억해서 쿵!':'쿵 소리를 기억하세요. 에취는 빼고!';
  const show=r.kind!=='play'||round<r.config.hints;let dots='';for(let i=0;i<4;i++)dots+=`<span class="${Math.floor(phase%4)===i?'on':''}">${i+1}</span>`;$('dkBeats').innerHTML=dots;$('dkBeats').classList.toggle('dk-clouded',r.kind==='play'&&(r.config.flour.includes(round)));$('dkHint').textContent=show?'사부: 앞 네 박 → 나: 뒤 네 박 · 에취에는 멈추기':'박자 힌트 없이 도전! · 스페이스바 / 터치 · Esc 일시정지';draw($('dkWorld'),b,r);raf=requestAnimationFrame(frame);
 }
 function finish(){const r=state,accuracy=DokkaebiChart.accuracy(r),rank=accuracy>=95?'S':accuracy>=80?'A':accuracy>=60?'B':'C';if(r.kind==='play'&&(!record||r.score>record.score)){record={score:r.score,accuracy};stageRecords[r.stage]=record;try{localStorage.setItem('rp-dokkaebi-stages',JSON.stringify(stageRecords));}catch{}}stopGame();$('dkResultTitle').textContent=r.kind==='demo'?'이제 직접 쳐볼까요?':`${r.config.name} · ${rank} · ${accuracy>=80?'찰떡 도사 탄생!':'떡방아 수업 완료'}`;$('dkSummary').textContent=`${r.score.toLocaleString()}점 · 정확도 ${accuracy}% · 최대 ${r.max}콤보`;$('dkDetail').textContent=`찰떡 ${r.perfect} / 성공 ${r.good} / 놓침 ${r.miss} · 가짜 신호 피하기 ${r.dodged}/${r.baits.filter(n=>!n.call).length}${r.kind!=='play'?' · 연습 기록은 저장하지 않아요':''}`;$('dkRetry').onclick=()=>start(r.kind==='demo'?'play':r.kind);nextTip(r,accuracy);$('dkResult').showModal();}
 // 수업이 끝나면 다음 라운드가 무엇인지 알려 주는 말풍선.
 function nextTip(r,accuracy){
  const last=r.stage>=DokkaebiChart.stages.length-1,target=r.kind==='demo'?r.stage:last?0:r.stage+1,config=DokkaebiChart.stages[target],kind=r.kind==='demo'?'play':r.kind;
  $('dkTip').innerHTML=r.kind==='demo'
   ?'시범은 여기까지! 이제 <b>'+config.name+'</b>을(를) 직접 쳐 볼 차례예요.'
   :last
    ?'모든 떡방아 수업을 마쳤어요! <b>'+config.name+'</b>부터 다시 돌며 기록을 갱신해 볼까요?'
    :(accuracy>=70?'좋아요! 다음 라운드는 ':'조금 더 익히고 싶다면 다시 도전, 바로 가려면 ')+'<b>'+config.name+'</b> · '+config.level+' · '+config.bpm+' BPM<br>'+config.desc;
  $('dkNext').textContent=r.kind==='demo'?'직접 떡 만들기 →':last?'첫 라운드로 →':'다음 라운드 →';
  $('dkNext').onclick=()=>{$('dkResult').close();selectedStage=target;record=stageRecords[target]||null;start(kind);};
 }
 function draw(canvas,b,r){DokkaebiArt.draw(canvas,b,r,selectedStage);}

 tab.onclick=()=>window.RhythmModes.switchMode('dokkaebi');$('dkStart').onclick=()=>start('play');$('dkPractice').onclick=()=>start('practice');$('dkDemo').onclick=()=>start('demo');$('dkBack').onclick=menu;$('dkDone').onclick=menu;$('dkPause').onclick=pause;$('dkResume').onclick=pause;$('dkSettings').onclick=()=>$('settingsDialog').showModal();$('dkResult').addEventListener('cancel',e=>{e.preventDefault();menu();});
 $('dkTap').onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();$('dkTap').setPointerCapture?.(e.pointerId);hit();};$('dkTap').onpointerup=release;$('dkTap').onpointercancel=release;$('dkTap').onlostpointercapture=release;$('dkTap').onclick=e=>{if(e.detail===0){hit();release();}};
 document.addEventListener('keydown',e=>{if(!active||!state||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)hit();}if(e.code==='Escape'){e.preventDefault();if(!e.repeat)pause();}});document.addEventListener('keyup',e=>{if(active&&e.code==='Space')release();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state&&!state.paused)pause();});window.addEventListener('blur',()=>{if(state&&!state.paused)pause();});
 $('dkSettings').onclick=()=>{if(state&&!state.paused)pause();$('settingsDialog').showModal();};
 window.Dokkaebi={open,stop};
})();

